version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: task-manager-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: task-manager
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-manager-network

  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task-manager-network

volumes:
  mongodb_data:
  redis_data:

networks:
  task-manager-network:
    driver: bridge
